- id: Joshua_Morning_Departure
  alias: "Joshua Morning Work Departure"
  trigger:
    platform: time
    at: '05:40:00'
  condition:
  - condition: and
    conditions: 
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.morning_work_departure

- id: Sunrise_Procedure
  alias: "Sunrise Procedure"
  trigger:
    platform: sun
    event: sunrise
    offset: "00:00:00"
  action:
    service: script.sunrise_procedure

- id: Sunset_Procedure
  alias: "Sunset Procedure"
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: script.sunset_procedure

- id: Home_Assistant_Update_Notification
  alias: Home Assistant Update Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: script.update_notification

- id: Bedroom_Motion_Detection_Alert
  alias: Bedroom Motion Detection Alert
  trigger:
    platform: state
    entity_id: sensor.master_bedroom_camera_motion_detected
    from: 'False'
    to: 'True'
  action:
    service: script.alert_bedroom_motion

- id: CR10S_S4_Print_Finished_Alert
  alias: CR10S S4 Print Finished Alert
  trigger:
    platform: state
    entity_id: sensor.creality_cr10s_s4_current_state
    from: 'Printing from SD'
  action:
    service: script.cr10s_s4_print_finished_alert

- id: Ender_3_Print_Finished_Alert
  alias: Ender 3 Print Finished Alert
  trigger:
    platform: state
    entity_id: sensor.creality_ender_3_current_state
    from: 'Printing from SD'
  action:
    service: script.ender_3_print_finished_alert

- id: Turn_Off_Christmas_Lights
  alias: Turn off Christmas lights
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    - condition: state
      entity_id: 'sensor.christmas_season'
      state: 'true'
  action:
    service: homeassistant.turn_off
    entity_id: group.christmas_lights