homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include misc/customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

hassio:
frontend:
config:
updater:
discovery:
logbook:
sun:

http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem  
  ssl_key: /ssl/privkey.pem  

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

#switch:
#  - platform: mqtt
#    name: "Table Light"
#    command_topic: "cmnd/LiquorLamp1/power"
#    state_topic: "stat/LiquorLamp1/POWER"
#    qos: 1
#    payload_on: "ON"
#    payload_off: "OFF"
#    retain: true

#Emulated Hue (For Echo Support)
emulated_hue:
  expose_by_default: false
  host_ip: !secret ha_ip_address
  listen_port: 8300
  exposed_domains:
    - light
    - switch

ecobee:
  api_key: !secret ecobee_api_key

octoprint:
  host: !secret octoprint_host_ip
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

abode:
  username: !secret abode_username
  password: !secret abode_password
  name: Abode Alarm System
  polling: False

joaoapps_join:
  - name: Pixel2XL
    device_id: !secret pixel2xl_id
    api_key: !secret join_api_key

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 10000
  network_key: !secret zwave_network_key


#amcrest:
#  - host: !secret ip_address_master_bedroom_camera
#    name: Master Bedroom Camera
#    username: !secret amcrest_username
#    password: !secret amcrest_password
#    sensors:
#      - motion_detector
#      - sdcard
#  - host: !secret ip_address_3d_printer_camera
#    name: 3D Printer Camera
#    username: !secret amcrest_username
#    password: !secret amcrest_password
#    sensors:
#      - motion_detector
#      - sdcard
#  - host: !secret ip_address_living_room_camera
#    name: Living Room Camera
#    username: !secret amcrest_username
#    password: !secret amcrest_password
#    sensors:
#      - motion_detector
#      - sdcard

#ring:
#  username: !secret ring_username
#  password: !secret ring_password

#device_tracker:
#  - platform: google_maps
#    username: !secret second_google_account_email
#    password: !secret second_google_account_password

#tts:
#  - platform: google
#    cache: true
#    cache_dir: /tmp/tts
#    time_memory: 300

alexa:
amcrest: !include_dir_list amcrest/
dialogflow:
intent_script: !include intent_script.yaml
automation: !include automations.yaml
group: !include groups.yaml
device-tracker: !include_dir_list device-trackers/
notify: !include_dir_list notifications/
remote: !include_dir_list remotes/
script: !include_dir_merge_named scripts/
sensor: !include_dir_list sensors/
switch: !include_dir_list switches/
tts: !include_dir_list tts/