homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include misc/customize.yaml
  auth_providers:
   - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml
config:
updater:
logbook:
logger:
sun:
system_health:
discovery:
mobile_app:

cloud:
  alexa:
    filter:
      exclude_domains:
        - media_player

http:
  base_url: !secret http_base_url

mqtt:
  broker: !secret mqtt_ip_address
  username: !secret mqtt_username
  password: !secret mqtt_password

ecobee:
  api_key: !secret ecobee_api_key

abode:
  username: !secret abode_username
  password: !secret abode_password

joaoapps_join:
  - name: JoshuaAndroidDevice
    device_id: !secret joshua_android_id
    api_key: !secret join_api_key

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 10000
  network_key: !secret zwave_network_key

input_boolean:
  goodnight_mode:
    name: Goodnight Mode
    initial: off
    icon: mdi:weather-night

automation: !include_dir_list automations/
cover: !include_dir_list covers/
intent_script: !include intent_script.yaml
group: !include groups.yaml
light: !include_dir_list lights/
notify: !include_dir_list notifications/
octoprint: !include_dir_list octoprint/
script: !include_dir_merge_named scripts/
sensor: !include_dir_list sensors/
switch: !include_dir_list switches/
tts: !include_dir_list tts/
weather: !include_dir_list weather/