homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include misc/customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

hassio:
frontend:
  themes: !include themes.yaml
lovelace:
  mode: yaml
config:
updater:
discovery:
logbook:
sun:

http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem  
  ssl_key: /ssl/privkey.pem  

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

#Emulated Hue (For Echo Support)
emulated_hue:
  expose_by_default: false
  host_ip: !secret ha_ip_address
  listen_port: 8300
  exposed_domains:
    - light
    - switch

ecobee:
  api_key: !secret ecobee_api_key

panel_iframe:
  cr10s4:
    title: 'CR-10S S4'
    url: !secret octoprint_cr10s_s4_url
    icon: mdi:printer-3d
  ender3:
    title: 'Ender 3'
    url: !secret octoprint_ender3_url
    icon: mdi:printer-3d

octoprint:
  - host: !secret octoprint_cr10s_s4_host_ip
    api_key: !secret octoprint_cr10s_s4_api_key
    name: Creality CR-10S S4
    bed: true
    number_of_tools: 1
  - host: !secret octoprint_ender3_host_ip
    api_key: !secret octoprint_ender3_api_key
    name: Creality Ender 3
    bed: true
    number_of_tools: 1

abode:
  username: !secret abode_username
  password: !secret abode_password
  name: Abode Alarm System
  polling: False

joaoapps_join:
  - name: JoshuaAndroidDevice
    device_id: !secret joshua_android_id
    api_key: !secret join_api_key

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 10000
  network_key: !secret zwave_network_key

ring:
  username: !secret ring_username
  password: !secret ring_password

weather:
  - platform: darksky
    api_key: !secret dark_sky_api

alexa:
amcrest: !include_dir_list amcrest/
dialogflow:
intent_script: !include intent_script.yaml
automation: !include automations.yaml
group: !include groups.yaml
device_tracker: !include_dir_list device-trackers/
notify: !include_dir_list notifications/
script: !include_dir_merge_named scripts/
sensor: !include_dir_list sensors/
switch: !include_dir_list switches/
tts: !include_dir_list tts/