
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: 192.168.1.98:8123

remote:
  - platform: harmony
    name: 'Living Room'
    host: 192.168.20.38
    activity: Play Xbox

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com

panel_iframe:
  portainer:
    title: Portainer
    icon: mdi:ferry
    url: https://portainer.fourthechelonhq.com/
  sonarr:
    title: Sonarr
    icon: mdi:television-box
    url: https://sonarr.fourthechelonhq.com/
  radarr:
    title: Radarr
    icon: mdi:movie
    url: https://radarr.fourthechelonhq.com/
  nbzget:
    title: NZBGet
    icon: mdi:progress-download
    url: https://nzbget.fourthechelonhq.com/
  transmission:
    title: Transmission
    icon: mdi:car-shift-pattern
    url: https://transmission.fourthechelonhq.com/
  jackett:
    title: Jackett
    icon: mdi:tshirt-crew
    url: https://jackett.fourthechelonhq.com/

# PiHole
pi_hole: 
  - host: !secret pihole_ipadress
    api_key: !secret pihole_api

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
cover: !include_dir_list covers/
group: !include groups.yaml
light: !include_dir_list lights/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_list sensors/
switch: !include_dir_list switches/