title: Joshua's Home
views:
  - title: Home
    icon: mdi:home-assistant
    cards:
      - type: vertical-stack
        cards:
        - type: weather-forecast
          entity: weather.dark_sky
        - type: entities
          title: Weather Info
          show_header_toggle: true
          entities:
            - sun.sun
            - sensor.moon
            - sensor.pws_alerts
            - sensor.pws_weather
            - sensor.pws_temp_f
            - sensor.pws_precip_today_in
            - sensor.pws_relative_humidity
            - sensor.pws_visibility_mi
      - type: vertical-stack
        cards:
        - type: picture-glance
          title: Master Bedroom Camera
          entities: 
            - light.mbr_light_level
            - sensor.master_bedroom_camera_motion_detected
            - sensor.master_bedroom_camera_sd_used
          camera_image: camera.master_bedroom_camera
        - type: picture-glance
          title: 3D Printer Camera
          entities:
            - sensor.3d_printer_camera_motion_detected
            - sensor.3d_printer_camera_sd_used
          camera_image: camera.3d_printer_camera
        - type: picture-glance
          title: Living Room Camera
          entities: 
            - light.living_room_ligh_level
            - light.nook_light_level
            - switch.living_room_fan_switch
            - sensor.living_room_camera_motion_detected
            - sensor.living_room_camera_sd_used
          camera_image: camera.living_room_camera
      - type: conditional
        conditions:
          - entity: switch.creality_cr10s_s4_switch
            state: "on"
        card:
          type: entities
          title: Creality CR10S S4
          show_header_toggle: true
          entities:
            - switch.creality_cr10s_s4_switch
            - binary_sensor.creality_cr10s_s4_printing
            - binary_sensor.creality_cr10s_s4_printing_error
            - sensor.creality_cr10s_s4_job_percentage
            - sensor.creality_cr10s_s4_target_bed_temp
            - sensor.creality_cr10s_s4_actual_bed_temp
            - sensor.creality_cr10s_s4_target_tool0_temp
            - sensor.creality_cr10s_s4_actual_tool0_temp
            - sensor.creality_cr10s_s4_current_state
            - sensor.creality_cr10s_s4_time_elapsed
            - sensor.creality_cr10s_s4_time_remaining
      - type: conditional
        conditions:
          - entity: switch.ender_3_switch
            state: "on"
        card:
          type: entities
          title: Ender 3
          show_header_toggle: true
          entities:
            - switch.ender_3_switch
            - binary_sensor.creality_ender_3_printing
            - binary_sensor.creality_ender_3_printing_error
            - sensor.creality_ender_3_job_percentage
            - sensor.creality_ender_3_target_bed_temp
            - sensor.creality_ender_3_actual_bed_temp
            - sensor.creality_ender_3_target_tool0_temp
            - sensor.creality_ender_3_actual_tool0_temp
            - sensor.creality_ender_3_current_state
            - sensor.creality_ender_3_time_elapsed
            - sensor.creality_ender_3_time_remaining
      - type: entities
        title: Virtual Sensors
        show_header_toggle: true
        entities:
          - device_tracker.google_maps_112239156454675366879
          - sensor.christmas_season
  - title: 3D Printers
    icon: mdi:printer-3d
    cards:
      - type: entities
        title: Creality CR10S S4
        show_header_toggle: true
        entities:
          - switch.creality_cr10s_s4_switch
          - binary_sensor.creality_cr10s_s4_printing
          - binary_sensor.creality_cr10s_s4_printing_error
          - sensor.creality_cr10s_s4_job_percentage
          - sensor.creality_cr10s_s4_target_bed_temp
          - sensor.creality_cr10s_s4_actual_bed_temp
          - sensor.creality_cr10s_s4_target_tool0_temp
          - sensor.creality_cr10s_s4_actual_tool0_temp
          - sensor.creality_cr10s_s4_current_state
          - sensor.creality_cr10s_s4_time_elapsed
          - sensor.creality_cr10s_s4_time_remaining
      - type: entities
        title: Ender 3
        show_header_toggle: true
        entities:
          - switch.ender_3_switch
          - binary_sensor.creality_ender_3_printing
          - binary_sensor.creality_ender_3_printing_error
          - sensor.creality_ender_3_job_percentage
          - sensor.creality_ender_3_target_bed_temp
          - sensor.creality_ender_3_actual_bed_temp
          - sensor.creality_ender_3_target_tool0_temp
          - sensor.creality_ender_3_actual_tool0_temp
          - sensor.creality_ender_3_current_state
          - sensor.creality_ender_3_time_elapsed
          - sensor.creality_ender_3_time_remaining        
  - title: Lights / Switches
    icon: mdi:lightbulb
    cards:
      - type: entities
        title: All Lights
        show_header_toggle: true
        entities:
          - light.back_floodlights_level
          - light.back_porch_light_level
          - light.front_floodlight_level
          - light.front_porch_ligh_level
          - light.garage_entry_lt_level
          - light.kitchen_bar_lt_level
          - light.kitchen_glass_lt_level
          - light.kitchen_sink_lt_level
          - light.living_room_ligh_level
          - light.loft_area_light_level
          - light.mbr_light_level
          - light.mbr_outlet_level
          - light.nook_light_level
          - light.office_light_level
          - light.primary_garage_l_level
          - light.stairway_light_level
      - type: entities
        title: All Switches
        show_header_toggle: true
        entities:
          - switch.creality_cr10s_s4_switch
          - switch.bar_outlet_switch
          - switch.dragon_tech_unknown_type4447_id3031_switch
          - switch.ext_lr_outlet_switch
          - switch.living_room_fan_switch
          - switch.lock_doors_on_away_arm
          - switch.lock_doors_on_home_arm
          - switch.mbr_fan_switch
          - switch.office_leds
          - switch.tv_leds_switch
          - switch.front_porch_outlet
      - type: entities
        title: All Kitchen Lights
        show_header_toggle: true
        entities:
          - light.kitchen_sink_lt_level
          - light.kitchen_glass_lt_level
          - light.kitchen_bar_lt_level
          - switch.dragon_tech_unknown_type4447_id3031_switch
  - title: Automation / Scripts
    icon: mdi:creation
    cards:
      - type: entities
        title: All Automations
        show_header_toggle: true
        entities:
          - automation.bedroom_motion_detection_alert
          - automation.home_assistant_update_notification
          - automation.joshua_morning_work_departure
          - automation.sunrise_procedure
          - automation.sunset_procedure
          - automation.cr10s_s4_print_finished_alert
          - automation.ender_3_print_finished_alert
      - type: entities
        title: All Scripts
        show_header_toggle: true
        entities:
          - script.all_lights_off
          - script.all_lights_on
          - script.joshua_bedtime
          - script.morning_work_departure
          - script.sunrise_procedure
          - script.sunset_procedure
          - script.update_notification
          - script.cr10s_s4_print_finished_alert
          - script.ender_3_print_finished_alert
  - title: Cameras
    icon: mdi:cctv
    cards:
      - type: picture-glance
        title: Master Bedroom Camera
        entities: 
          - light.mbr_light_level
          - sensor.master_bedroom_camera_motion_detected
          - sensor.master_bedroom_camera_sd_used
        camera_image: camera.master_bedroom_camera
      - type: picture-glance
        title: 3D Printer Camera
        entities:
          - sensor.3d_printer_camera_motion_detected
          - sensor.3d_printer_camera_sd_used
        camera_image: camera.3d_printer_camera
      - type: picture-glance
        title: Living Room Camera
        entities: 
          - light.living_room_ligh_level
          - light.nook_light_level
          - switch.living_room_fan_switch
          - sensor.living_room_camera_motion_detected
          - sensor.living_room_camera_sd_used
        camera_image: camera.living_room_camera