title: Joshua's Home
resources:
  - url: /local/monster-card.js
    type: js
views:
  - title: Home
    icon: mdi:home-assistant
    cards:
      - type: vertical-stack
        cards:
        - type: weather-forecast
          entity: weather.dark_sky
        - type: entities
          title: Status Info
          show_header_toggle: false
          entities:
            - sun.sun
            - sensor.moon
            - sensor.christmas_season
            - input_boolean.goodnight_mode
        - type: entities
          title: Common
          show_header_toggle: false
          entities:
            - script.bedtime_joshua
            - script.sunrise_procedure
            - script.sunset_procedure
      - type: vertical-stack
        cards:
          - type: thermostat
            name: Main Floor
            entity: climate.main_floor
          - type: thermostat
            name: Upstairs
            entity: climate.upstairs
      - type: conditional
        conditions:
          - entity: sensor.christmas_season
            state: "true"
        card:
          type: entities
          title: Holiday Lights
          show_header_toggle: false
          entities:    
            - light.holiday_lights
            - light.holiday_color_1
            - light.holiday_color_2
            - light.holiday_color_3
            - light.holiday_glitter
            - light.holiday_lightning
            - sensor.current_led
      - type: conditional
        conditions:
          - entity: switch.creality_cr10s_s4_switch
            state: "on"
        card:
          type: entities
          title: Creality CR10S S4
          show_header_toggle: true
          entities:
            - binary_sensor.creality_cr_10s_s4_printing
            - binary_sensor.creality_cr_10s_s4_printing_error
            - sensor.creality_cr_10s_s4_job_percentage
            - sensor.creality_cr_10s_s4_target_bed_temp
            - sensor.creality_cr_10s_s4_actual_bed_temp
            - sensor.creality_cr_10s_s4_target_tool0_temp
            - sensor.creality_cr_10s_s4_actual_tool0_temp
            - sensor.creality_cr_10s_s4_current_state
            - sensor.creality_cr_10s_s4_time_elapsed
            - sensor.creality_cr_10s_s4_time_remaining
      - type: conditional
        conditions:
          - entity: switch.ender_3_switch
            state: "on"
        card:
          type: entities
          title: Ender 3
          show_header_toggle: true
          entities:
            - switch.ender_3_switch
            - binary_sensor.creality_ender_3_printing
            - binary_sensor.creality_ender_3_printing_error
            - sensor.creality_ender_3_job_percentage
            - sensor.creality_ender_3_target_bed_temp
            - sensor.creality_ender_3_actual_bed_temp
            - sensor.creality_ender_3_target_tool0_temp
            - sensor.creality_ender_3_actual_tool0_temp
            - sensor.creality_ender_3_current_state
            - sensor.creality_ender_3_time_elapsed
            - sensor.creality_ender_3_time_remaining
  - title: 3D Printers
    icon: mdi:printer-3d
    cards:
      - type: entities
        title: Creality CR10S S4
        show_header_toggle: true
        entities:
          - switch.aeon_labs_dsc06106_smart_energy_switch_switch_3
          - binary_sensor.creality_cr_10s_s4_printing
          - binary_sensor.creality_cr_10s_s4_printing_error
          - sensor.creality_cr_10s_s4_job_percentage
          - sensor.creality_cr_10s_s4_target_bed_temp
          - sensor.creality_cr_10s_s4_actual_bed_temp
          - sensor.creality_cr_10s_s4_target_tool0_temp
          - sensor.creality_cr_10s_s4_actual_tool0_temp
          - sensor.creality_cr_10s_s4_current_state
          - sensor.creality_cr_10s_s4_time_elapsed
          - sensor.creality_cr_10s_s4_time_remaining
      - type: entities
        title: Ender 3
        show_header_toggle: true
        entities:
          - switch.aeon_labs_dsc06106_smart_energy_switch_switch_2
          - binary_sensor.creality_ender_3_printing
          - binary_sensor.creality_ender_3_printing_error
          - sensor.creality_ender_3_job_percentage
          - sensor.creality_ender_3_target_bed_temp
          - sensor.creality_ender_3_actual_bed_temp
          - sensor.creality_ender_3_target_tool0_temp
          - sensor.creality_ender_3_actual_tool0_temp
          - sensor.creality_ender_3_current_state
          - sensor.creality_ender_3_time_elapsed
          - sensor.creality_ender_3_time_remaining        
  - title: Lights / Switches
    icon: mdi:lightbulb
    cards:
      - type: entities
        title: All Inside Lights
        show_header_toggle: true
        entities:
          - light.garage_entry_lt_level
          - light.kitchen_bar_lt_level
          - light.kitchen_glass_lt_level
          - light.kitchen_sink_lt_level
          - light.living_room_ligh_level
          - light.loft_area_light_level
          - light.mbr_light_level
          - light.mbr_outlet_level
          - light.nook_light_level
          - light.office_light_level
          - light.primary_garage_l_level
          - light.stairway_light_level
      - type: entities
        title: All Outside Lights
        show_header_toggle: true
        entities:
          - light.back_floodlights_level
          - light.back_porch_light_level
          - light.front_porch_ligh_level
          - light.unknown_node_13_level
      - type: entities
        title: All Switches
        show_header_toggle: true
        entities:
          - switch.aeon_labs_dsc06106_smart_energy_switch_switch
          - switch.aeon_labs_dsc06106_smart_energy_switch_switch_2
          - switch.aeon_labs_dsc06106_smart_energy_switch_switch_3
          - switch.bar_outlet_switch
          - switch.dragon_tech_unknown_type_4447_id_3031_switch
          - switch.ext_lr_outlet_switch
          - switch.living_room_fan_switch
          - switch.mbr_fan_switch
          - switch.office_leds
          - switch.coffee_table_lamp
          - switch.front_porch_outl_switch
          - switch.holiday_lights_main
          - cover.motorized_blinds
      - type: entities
        title: All Kitchen Lights
        show_header_toggle: true
        entities:
          - light.kitchen_sink_lt_level
          - light.kitchen_glass_lt_level
          - light.kitchen_bar_lt_level
          - switch.dragon_tech_unknown_type_4447_id_3031_switch
  - title: Automation / Scripts
    icon: mdi:creation
    cards:
      - type: entities
        title: All Automations
        show_header_toggle: true
        entities:
          - automation.cr10s_s4_print_finished_alert
          - automation.ender_3_print_finished_alert
          - automation.goodnight_routine
          - automation.home_assistant_update_notification
          - automation.joshua_morning_work_departure
          - automation.set_theme_at_startup
          - automation.sunrise_procedure
          - automation.sunset_procedure
          - automation.turn_off_holiday_lights
      - type: entities
        title: All Scripts
        show_header_toggle: false
        entities:
          - script.all_lights_off
          - script.all_lights_on
          - script.bedtime_joshua
          - script.cr10s_s4_print_finished_alert
          - script.ender_3_print_finished_alert
          - script.morning_work_departure
          - script.sunrise_procedure
          - script.sunset_procedure
          - script.turn_off_holiday_lights
          - script.turn_on_holiday_lights
          - script.update_notification
  - title: Plex
    icon: mdi:plex
    cards:
      - type: "custom:monster-card"
        card:
          type: entities
          show_header_toggle: false
        filter:
          include:
            - entity_id: media_player.plex*
  - title: Plex
    icon: mdi:network
    cards:
      - type: "custom:monster-card"
        card:
          type: entities
          show_header_toggle: false
        filter:
          include:
            - entity_id: device_tracker*