id: Ender_3_Print_Finished_Alert
alias: Ender 3 Print Finished Alert
hide_entity: false
initial_state: true
trigger:
  platform: state
  entity_id: sensor.creality_ender_3_current_state
  from: 'Printing from SD'
action:
  service: script.ender_3_print_finished_alert