id: Goodnight_Routine
alias: "Goodnight Routine"
hide_entity: false
initial_state: true
trigger:
  platform: state
  entity_id: input_boolean.goodnight_mode
  to: 'on'
action:
  service: script.bedtime_joshua