id: Turn_Off_Holiday_Lights
alias: Turn off Holiday lights
hide_entity: false
initial_state: true
trigger:
  platform: state
  entity_id: light.mbr_outlet_level
condition:
  - condition: state
    entity_id: 'light.mbr_outlet_level'
    state: 'off'
action:
  service: script.turn_off_bed_lights